import tinymce from 'tinymce/tinymce';

tinymce.addI18n('lt', {
    Accessibility: 'Prieinamumas',
    Advanced: 'I\u0161pl\u0117stiniai nustatymai',
    Alignment: 'Lygiavimas',
    Apply: 'Taikyti',
    'Alternative description': 'Alternatyvus apra\u0161ymas',
    'Align center': 'Lygiuoti centre',
    'Align left': 'Lygiuoti kair\u0117je',
    'Align right': 'Lygiuoti de\u0161in\u0117je',
    Bold: 'Pary\u0161kinti',
    'Border style': 'R\u0117melio stilius',
    'Border width': 'R\u0117melio storis',
    'Browse files': 'Pasirinkti failus',
    'Browse for an image': 'Pasirinkti nuotrauk\u0105',
    'Bullet list': '\u017denklintas s\u0105ra\u0161as',
    Cancel: 'At\u0161aukti',
    Caption: 'Antra\u0161t\u0117',
    Center: 'Centre',
    Class: 'Lygiavimas',
    Close: 'U\u017edaryti',
    Code: 'HTML kodas',
    'Constrain proportions': 'I\u0161laikyti proporcijas',
    Dashed: 'Br\u016bk\u0161ninis',
    'Decrease indent': 'Ma\u017einti \u012ftrauk\u0105',
    Dimensions: 'Matmenys',
    Dotted: 'Ta\u0161kinis',
    Double: 'Dvigubas',
    'Drop an image here': 'Nutempkite nuotrauk\u0105 \u010dia',
    Edit: 'Redaguoti',
    'Failed to upload image': 'Nepavyko \u012fkelti nuotraukos.',
    File: 'Failas',
    Format: 'Formatas',
    Formats: 'Formatai',
    General: 'Bendra',
    Groove: 'Griovelinis',
    Height: 'Auk\u0161tis',
    'Heading 1': 'Antra\u0161t\u0117 1',
    'Heading 2': 'Antra\u0161t\u0117 2',
    'Heading 3': 'Antra\u0161t\u0117 3',
    Hidden: 'Pasl\u0117ptas',
    'Horizontal space': 'Horizontalus tarpas',
    Image: 'Nuotrauka',
    'Image is decorative': 'Dekoratyvin\u0117 nuotrauka',
    'Image list': 'Nuotrauk\u0173 s\u0105ra\u0161as',
    'Image title': 'Pavadinimas',
    'Image...': 'Nuotrauka...',
    'Increase indent': 'Didinti \u012ftrauk\u0105',
    Inset: '\u012espaustas',
    Insert: '\u012eterpti',
    'Insert/Edit Image': '\u012eterpti / redaguoti nuotrauk\u0105',
    'Insert/edit image': '\u012eterpti / redaguoti nuotrauk\u0105',
    'Insert/edit link': '\u012eterpti / redaguoti nuorod\u0105',
    Italic: 'Kursyvas',
    Left: 'Kair\u0117je',
    Link: 'Nuoroda',
    'Loading...': 'Kraunama...',
    'No alignment': 'Be lygiavimo',
    None: 'N\u0117ra',
    'Numbered list': 'Numeruotas s\u0105ra\u0161as',
    Outset: '\u012e\u0161keltas',
    Paragraph: 'Pastraipa',
    Redo: 'Gr\u0105\u017einti',
    Remove: 'Pa\u0161alinti',
    Ridge: 'I\u0161kilus',
    Right: 'De\u0161in\u0117je',
    Save: 'I\u0161saugoti',
    'Select...': 'Pasirinkite...',
    'Show caption': 'Rodyti antra\u0161t\u0119',
    Solid: 'Vientisas',
    Source: 'Nuotraukos adresas',
    Style: 'Stilius',
    Tools: '\u012erankiai',
    Undo: 'At\u0161aukti veiksm\u0105',
    Upload: '\u012ekelti',
    'Failed to upload image: {0}': 'Nepavyko \u012fkelti nuotraukos: {0}',
    'Image uploading...': 'Nuotrauka \u012fkeliama...',
    'Upload image': '\u012ekelti nuotrauk\u0105',
    'Uploading image': 'Nuotrauka \u012fkeliama',
    'Vertical space': 'Vertikalus tarpas',
    View: 'Per\u017ei\u016bra',
    'Visual aids': 'Vaizdin\u0117s pagalbos',
    Width: 'Plotis',
});
