@extends('layouts.admin')
@section('content')
<div class="admin-page wordpress-migration">
 <div class="admin-page__header"><div><h1 class="admin-page__title">Bandomasis importas</h1><p>Jokie svetainės duomenys dar nepakeisti.</p></div></div>
 @if(session('error'))<div class="admin-alert admin-alert--danger" role="alert">{{ session('error') }}</div>@endif
 @if(!$plan)
 <section class="admin-panel" aria-live="polite"><h2>{{ ($manifest['dry_run_status'] ?? null) === 'failed' ? 'Bandomasis importas nepavyko' : 'Bandomasis importas rengiamas' }}</h2><p>{{ $manifest['dry_run_error'] ?? 'Planas saugiai rengiamas eilėje. Jokie svetainės duomenys nekeičiami.' }}</p>@if(($manifest['dry_run_status'] ?? null) !== 'failed')<p>Jei būsena ilgai nesikeičia, paleiskite <code>php artisan queue:work --tries=3 --timeout=360</code>.</p>@endif</section>
 @else
 <section class="admin-panel"><h2>Prognozė</h2><div class="wordpress-migration__ready-summary">@foreach(['create'=>'Bus sukurta','update'=>'Bus atnaujinta','skip'=>'Bus praleista','media_references'=>'Medijos nuorodos','redirects'=>'Peradresavimai','chunks'=>'Eilės dalys'] as $key=>$label)<div><strong>{{ $plan['forecast'][$key] }}</strong><span>{{ $label }}</span></div>@endforeach</div></section>
 @if($plan['blocking_errors'])<section class="admin-panel"><h2>Blokuojančios klaidos</h2><ul>@foreach($plan['blocking_errors'] as $message)<li>{{ $message }}</li>@endforeach</ul></section>@endif
 @if($plan['warnings'])<details class="admin-panel"><summary>Perspėjimai ({{ count($plan['warnings']) }})</summary><ul>@foreach($plan['warnings'] as $message)<li>{{ $message }}</li>@endforeach</ul></details>@endif
 <details class="admin-panel"><summary>URL, slug ir konfliktų peržiūra ({{ count($plan['items']) }})</summary><div class="admin-table-wrapper"><table class="admin-table"><thead><tr><th>Straipsnis</th><th>Veiksmas</th><th>Slug</th><th>Naujas URL</th><th>Medija</th></tr></thead><tbody>@foreach($plan['items'] as $item)<tr><td>{{ $item['title'] }}</td><td>{{ $item['action'] }}</td><td>{{ $item['source_slug'] }} → {{ $item['final_slug'] }}</td><td>{{ $item['target_url'] }}</td><td>{{ count($item['media_urls']) + ($item['featured_image_url'] ? 1 : 0) }}</td></tr>@endforeach</tbody></table></div></details>
 <details class="admin-panel"><summary>Praleidžiami įrašai ({{ count($plan['skipped']) }})</summary><ul>@foreach($plan['skipped'] as $item)<li>{{ $item['title'] ?: 'Be pavadinimo' }} — {{ $item['reason'] }}</li>@endforeach</ul></details>
 <div class="wordpress-migration__completion-actions"><a class="admin-button admin-button--secondary" href="{{ route('admin.wordpress-migration.ready') }}">Atgal</a><form method="POST" action="{{ route('admin.wordpress-migration.dry-run', $manifest['id']) }}">@csrf<button class="admin-button admin-button--secondary" type="submit">Pakartoti bandomąjį importą</button></form></div>
 @if(!$plan['blocking_errors'])<section class="admin-panel"><h2>Pradėti tikrą importavimą</h2><p>Importavimas bus vykdomas fone. Prieš tęsdami paleiskite <code>php artisan queue:work --tries=3 --timeout=300</code>.</p><form method="POST" action="{{ route('admin.wordpress-migration.confirm', $manifest['id']) }}">@csrf<label><input type="checkbox" name="confirmed" value="1" required> Patvirtinu, kad peržiūrėjau bandomojo importo ataskaitą ir noriu pradėti importavimą.</label><label>Įrašykite IMPORTUOTI<input name="confirmation_phrase" required autocomplete="off"></label>@if(app()->environment(['local','testing']))<label>Kontroliuojamas testas<select name="test_limit"><option value="">Visas importas</option><option value="3">Pirmi 3 straipsniai</option><option value="5">Pirmi 5 straipsniai</option></select></label>@endif<button class="admin-button" type="submit">Pradėti importavimą</button></form></section>@endif
 @endif
</div>
@endsection
@if(!$plan && ($manifest['dry_run_status'] ?? null) !== 'failed')@push('head')<meta http-equiv="refresh" content="3">@endpush@endif
