@extends('layouts.admin')
@section('content')
<div class="admin-page wordpress-migration wordpress-migration__step-content">
    <div class="admin-page__header"><h1 class="admin-page__title">WordPress importavimo centras</h1></div>
    @include('admin.partials.wordpress-migration-wizard')
    <section class="wordpress-migration__status-card is-info"><span>ℹ</span><div><strong>SEO nustatymai</strong><p>Pasirinkite, kaip būsimo importavimo metu tvarkyti adresus ir paieškos sistemoms skirtą informaciją.</p></div></section>
    <section class="admin-panel admin-form-panel"><form class="admin-form admin-form--full" method="POST" action="{{ route('admin.wordpress-migration.seo.update') }}" data-migration-autosave data-success-message="SEO nustatymai išsaugoti" data-saved="{{ isset($manifest['seo_settings_saved_at']) ? '1' : '0' }}">@csrf @method('PUT')
        <div class="admin-form-card__header"><h2>SEO ir URL</h2><p>Pakeitimai išsaugomi automatiškai. Dabar svetainės duomenys nekeičiami.</p></div>
        <fieldset class="wordpress-migration__fieldset"><legend>Adresų konfliktai</legend><p class="admin-form__help-text">Ką daryti, jei toks puslapio adresas jau naudojamas?</p><div class="wordpress-migration__radio-list">@foreach(['skip'=>['Praleisti','Esamas turinys lieka nepakeistas.'],'overwrite'=>['Perrašyti','Esamas įrašas pakeičiamas importuojamu turiniu.'],'generate'=>['Sukurti naują adresą','Importuojamam įrašui sukuriamas unikalus adresas.']] as $value=>[$label,$description])<label><input type="radio" name="slug_conflicts" value="{{ $value }}" {{ ($manifest['seo_settings']['slug_conflicts'] ?? 'skip') === $value ? 'checked' : '' }}><span><strong>{{ $label }}</strong><small>{{ $description }}</small></span></label>@endforeach</div></fieldset>
        <fieldset class="wordpress-migration__fieldset"><legend>SEO informacija</legend><div class="wordpress-migration__option-grid">@foreach(['meta_title'=>['Puslapio pavadinimas','Perkeliamas paieškos rezultatuose rodomas pavadinimas.'],'meta_description'=>['Puslapio aprašymas','Perkeliamas trumpas paieškos rezultatų aprašymas.'],'canonical_url'=>['Pagrindinis puslapio adresas','Išsaugoma paieškos sistemoms skirta pagrindinio adreso nuoroda.']] as $key=>[$label,$description])<label class="wordpress-migration__option"><input type="checkbox" name="{{ $key }}" value="1" {{ ($manifest['seo_settings'][$key] ?? true) ? 'checked' : '' }}><span><strong>{{ $label }}</strong><small>{{ $description }}</small></span></label>@endforeach</div></fieldset>
        <fieldset class="wordpress-migration__fieldset"><legend>Peradresavimai</legend><div class="wordpress-migration__radio-list">@foreach(['none'=>['Nekurti','Seni adresai nebus automatiškai nukreipiami.'],'automatic'=>['Sukurti automatiškai','Seni WordPress adresai bus nukreipti į naujus puslapius.']] as $value=>[$label,$description])<label><input type="radio" name="redirect_handling" value="{{ $value }}" {{ ($manifest['seo_settings']['redirect_handling'] ?? 'none') === $value ? 'checked' : '' }}><span><strong>{{ $label }}</strong><small>{{ $description }}</small></span></label>@endforeach</div></fieldset>
        <div data-save-notice class="wordpress-migration__save-notice" role="status" aria-live="polite"></div>
        <div class="admin-form__actions"><a class="admin-button admin-button--secondary" href="{{ route('admin.wordpress-migration.settings') }}">Atgal</a><a class="admin-button admin-button--primary" data-continue href="{{ route('admin.wordpress-migration.ready') }}">Tęsti →</a></div>
    </form></section>
    @include('admin.partials.wordpress-migration-history')
</div>
@endsection
